pipelines:
    profile_pic_pipeline:
        concurrency: 50
        pipeline:
            dummy_processor1:
                next:
                    disk2:
                        async: false
            dummy_processor2:
                next:
                    dummy_processor1:
                        next:
                            disk1:
                                async: false
                    disk2:
                        async: false
            dummy_processor3:
                next:
                    dummy_processor4:
                        next:
                            disk4:
                                async: false
            dummy_processor5:
                next:
                    disk5:
                        async: false
            nude_censor:
                async: true
                next:
                    disk3:
                        async: false