pipelines:
    profile_pic_pipeline:
        concurrency: 50
        pipeline:
            validator:
                next:
                    resize_minimum:
                        next:
                            resize_big:
                                next:
                                    big:
                                        async: false
                            resize_medium:
                                next:
                                    smart_crop_thumbnail:
                                        next:
                                            thumbnail:
                                                async: false
                                    watermark_label:
                                        next:
                                            watermark:
                                                async: false
                                    medium:
                                        async: false
                            resize_small:
                                next:
                                    flip_blur:
                                        next:
                                            flipped_blurred:
                                                async: false
                                    small:
                                        async: false
                            original:
                                async: false