processors:
    dummy_processor1:
        concurrency: 10
        plugin: dummy_processor
        config:
            filename: testing.jpg
    dummy_processor2:
        concurrency: 10
        plugin: dummy_processor
        config:
            filename: testing.jpg
    dummy_processor3:
        plugin: dummy_processor
        concurrency: 10
        config:
            filename: testing.jpg